CREATE TABLE [dbo].[ApiResource]
(
	[Id]			[UNIQUEIDENTIFIER]	NOT NULL,
	[Description]	[NVARCHAR](1000)	NOT NULL DEFAULT(''),
	[DisplayName]	[NVARCHAR](200)		NOT NULL DEFAULT(''),
	[IsEnabled]		[BIT]				NOT NULL DEFAULT(1),
	[Name]			[NVARCHAR](200)		NOT NULL DEFAULT(''),
	[Secret]		[NVARCHAR](2000)	NOT NULL DEFAULT(''),
	[Ts]			[ROWVERSION]		NOT NULL,
	CONSTRAINT [PK_ApiResource_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [IDX_ApiResource_Name_U_N] UNIQUE NONCLUSTERED ([Name] ASC)
)