CREATE TABLE [dbo].[GrantType]
(
	[Id]	[INT]				NOT NULL IDENTITY(1,1),
	[Name]	[NVARCHAR](100)		NOT NULL DEFAULT(''),
	CONSTRAINT [PK_GrantType_Id] PRIMARY KEY CLUSTERED([Id] ASC),
	CONSTRAINT [IDX_GrantType_Name_U_N] UNIQUE NONCLUSTERED ([Name] ASC)
)