CREATE TABLE [dbo].[Role]
(
	[Id]					UNIQUEIDENTIFIER NOT NULL,
	[ConcurrencyStamp]		NVARCHAR(MAX) NULL,
	[Name]					NVARCHAR(256) NOT NULL DEFAULT(''),
	[NormalizedName]		NVARCHAR(256) NOT NULL DEFAULT(''),
	CONSTRAINT [PK_Role_Id] PRIMARY KEY CLUSTERED([Id] ASC),
	CONSTRAINT [IDX_Role_Name_U_N] UNIQUE NONCLUSTERED ([Name] ASC)
)