CREATE TABLE [dbo].[Template]
(
	[Id]	[INT]				NOT NULL IDENTITY(1,1),
	[Name]	[NVARCHAR](100)		NOT NULL DEFAULT(''),
	CONSTRAINT [PK_Template_Id] PRIMARY KEY CLUSTERED([Id] ASC),
	CONSTRAINT [IDX_Template_Name_U_N] UNIQUE NONCLUSTERED ([Name] ASC)
)
